### ISSUE TITLE
Reproduction attempt

### ISSUE THREAD

**Issue by nuest** [geoss/acs_demographic_clusters#2]
Thanks for providing data and code together with your article! I've attempted a reproduction as part of a manuscript under development, and was partly successful, which is really great. :tada: 

(and thanks for already fixing the license, #1)

Here is what I achieved and the changes I made and how far I got. I worked with the file `Data Analysis and Visualization.R`, as I was unsure about the differences between it and the Markdown file.

- add a few lines of code to download the data at the start
- make some educated guesses to fix non-existing objects: `X10`, `USA2`
- make an educated guess to use file `Input-Data/usa_trt_varnames_plots_0913.csv` instead of the missing `usa_trt_varnames.csv`
- moved CHECK MULTICOLLINEARITY code down so that `usa.trt.cl` is found (created later in the script
- make number of runs and iterations configurable, so that I had some results with much smaller waiting time > _I don't really worry about the actual results right now, just want to make sure the code runs_, I'm happy to run the long analysis (parallelize it?) when the code works.
- load library `cluster` so that `silhouette()` is available
- added a guess where `US_tract_2010.shp` could be downloaded
- try to fix deprecated ggplot2 function usage
- add a gitignore file, ignoring some R-specific stuff but also the data folders
- fixed a minor typo in the readme, replace some placeholders there, apply common Markdown formatting, fix headline formatting

You can see the changes in this comparison: https://github.com/geoss/acs_demographic_clusters/compare/master...nuest:master

### Results

I have a dendogram (of course looks different because of smaller number of runs)!

![image](https://user-images.githubusercontent.com/1325054/67939476-eb8af580-fbd1-11e9-8ce1-f5f977e25ce0.png)

I have Figure 10 (sort of) !

![image](https://user-images.githubusercontent.com/1325054/67939584-2c830a00-fbd2-11e9-8098-0addc103afc9.png)

I have another figure that looks quite bad...

![image](https://user-images.githubusercontent.com/1325054/67939710-6eac4b80-fbd2-11e9-8208-7cfdf49c7f2c.png)

**I look forward to your comments regarding the changes**. It would be great if you could help resolving some of the guesses I had to make.

**Comment by geoss** [comment]
DO you want to send a pull request?  That'll make it easy for me to review changes.  Thanks.  -SS
